<?php

echo
(
    "<!DOCTYPE html>
    <html lang='en'>

    <head>
    <meta charset='UTF-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>

    <link rel='stylesheet' href='css/brands.css'>
    <link rel='shortcut icon' href='img/favicon.png' type='image/png'>

    <link rel='preconnect' href='https://fonts.googleapis.com'>
    <link rel='preconnect' href='https://fonts.gstatic.com' crossorigin>
    <link href='https://fonts.googleapis.com/css2?family=Tilt+Warp&display=swap' rel='stylesheet'>

    <script src='https://kit.fontawesome.com/c8a9f34c0a.js' crossorigin='anonymous'></script>
    <script src='https://code.jquery.com/jquery-3.6.4.js' integrity='sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E='
        crossorigin='anonymous'></script>

    <title>Concept Collection</title>
    </head>

    <body>

    <svg id='loading' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'
        style='margin: auto; background: rgb(15, 25, 78); shape-rendering: auto;' width='200px' height='200px'
        viewBox='0 0 100 100' preserveAspectRatio='xMidYMid'>
        <path fill='none' stroke='#47b5ff' stroke-width='8' stroke-dasharray='42.76482137044271 42.76482137044271'
        d='M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z'
        stroke-linecap='round' style='transform:scale(0.8);transform-origin:50px 50px'>
        <animate attributeName='stroke-dashoffset' repeatCount='indefinite' dur='1s' keyTimes='0;1'
            values='0;256.58892822265625'></animate>
        </path>
        <!-- [ldio] generated by https://loading.io/ -->
    </svg>"
);

require_once "header.php";

echo
(
    "<section class='brands'>
    </section>"
);

require_once "footer.php";

echo
(
    "<script src='js/brands.js'></script>
    
    </body>
    
    </html>"
);

?>